#!/usr/bin/env python3
"""W40 probe: BFS (Best Face Swap) LoRA on Qwen-Image-2.1 — free T4.

Full test of https://huggingface.co/Alissonerdx/BFS-Best-Face-Swap for the
family the lab already runs (Qwen-Image-2.1 on T4, W39/W40 stack). BFS ships
LoRAs for head swap (v1.1 recommended), body swap (v1.0) and an optional Pruna
8-step accelerator; the official ComfyUI workflow drives two images through the
stock TextEncodeQwenImage21 node (Qwen3-VL tokens <image1>/<image2> + reference
latents via vae), KSampler 8 steps cfg 1.0 deis_2m, seed 42.

Consent-free by construction: all three input images (scene with FREE GPU LAB
neon canary, reference head, full-body reference) are generated by the lab's
proven viggle-r256 turbo pipeline at fixed seed — no real person involved, and
the whole run is reproducible from this file + timings JSON.

Rows (PLAN.md has the full matrix): official int8 recipe cold+warm at 1408²,
1024² speed row, no-BFS anchor, body swap, GGUF hook-loader vs stock-merge.
Ladders on sampler (deis_2m→res_2m→deis→res_multistep), autogrow API format,
merge→hook; every row's graph asserted distinct (W40 cache-hit lesson).
Server restarts between the int8 and GGUF blocks (12.7 GB RAM box).

T4 adaptation (attempt-3 measurement): the official template binds BOTH
references at the latent size (2 MP) — once conditioning actually works that is
~40k DiT sequence tokens and the sampler crawls at 258.8 s/step on the T4
(vs 11 s/step with the images silently unbound). References are therefore
pre-scaled down (scene 768², head 512² — the author's own "give the reference
room, not resolution" guidance from the body-swap doc); the latent stays at the
template sizes. Attempt history: (1) min_bytes floor killed the Pruna download;
(2) QwenImage21Cache required device/dtype widgets + a zombie server on 8188;
(3) nested-dict autogrow silently bound ZERO images (flat 'images.image_N' keys
are the real API format) — every swap row was pure t2i until this was fixed.
"""

import atexit
import hashlib
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from urllib.parse import quote as urlquote

# --- surface: prove by env, not paths (W40 lesson: Colab ships stray /kaggle) ---
SURFACE_PROOF = {
    "COLAB_GPU": os.environ.get("COLAB_GPU"),
    "KAGGLE_KERNEL_RUN_TYPE": os.environ.get("KAGGLE_KERNEL_RUN_TYPE"),
    "isdir_kaggle": os.path.isdir("/kaggle"),
    "isdir_content": os.path.isdir("/content"),
}
SURFACE = "kaggle" if os.environ.get("KAGGLE_KERNEL_RUN_TYPE") else "colab"
if SURFACE == "kaggle":
    C = "/tmp/ComfyUI"
    OUT = "/kaggle/working/out"
else:
    C = "/content/ComfyUI"
    OUT = "/content/out"
PORT = 8188
BASE = f"http://127.0.0.1:{PORT}"
SEED = 42
FLAGS = ["--force-fp16", "--disable-comfy-compiler"]

# --- weights ---
DIT_INT8_NAME = "qwen_image_2.1_int8_convrot.safetensors"
DIT_INT8_URL = ("https://huggingface.co/Comfy-Org/Qwen-Image-2.1/resolve/main/"
                f"diffusion_models/{DIT_INT8_NAME}")
GGUF_NAME = "qwen-image-2.1-Q4_K_M.gguf"
GGUF_URL = f"https://huggingface.co/unsloth/Qwen-Image-2.1-GGUF/resolve/main/{GGUF_NAME}"
TE_NAME = "qwen3vl_8b_int8_convrot.safetensors"
TE_URL = f"https://huggingface.co/abenzerps/Qwen-Image-2.1-GGUF/resolve/main/text_encoders/{TE_NAME}"
VAE_NAME = "qwen_image_2.1_vae_bf16.safetensors"
VAE_URL = f"https://huggingface.co/abenzerps/Qwen-Image-2.1-GGUF/resolve/main/vae/{VAE_NAME}"
BFS_BASE = "https://huggingface.co/Alissonerdx/BFS-Best-Face-Swap/resolve/main"
BFS_HEAD = "bfs_head_v1.1_qwen_2.1.safetensors"
BFS_BODY = "bfs_body_swap_v1.0_qwen_2.1.safetensors"
PRUNA_BASE = "https://huggingface.co/PrunaAI/Pruna-Qwen-Image-2.1/resolve/main"
LORA_PRUNA8 = "p_qwen_image_2.1_8step_v0.1.safetensors"
VIGGLE_BASE = "https://huggingface.co/Viggle/Qwen-Image-2.1-viggle-turbo/resolve/main"
LORA_VIGGLE_R256 = "Qwen-Image-2.1-viggle-turbo-v0.2.1-6step-lora-r256.safetensors"
NODES_URL = f"{VIGGLE_BASE}/comfyui/viggle_turbo.py"

SIGMAS_6 = "1.0, 0.9375, 0.875, 0.75, 0.5, 0.25"
SAMPLER_LADDER = ["deis_2m", "res_2m", "deis", "res_multistep"]

HEAD_PROMPT = ("head_swap: start with <image1> as the base image, keeping its lighting, "
               "environment, and background. remove the head from <image1> completely and "
               "replace it with the head from <image2>, strictly preserving the hair, eye "
               "color, nose structure from <image2>. copy the direction of the eye, head "
               "rotation, micro expressions from <image1>, high quality, sharp details, 4k")
BODY_PROMPT = ("body_swap: start with <image1> as the base image, keeping its lighting, "
               "environment, and background. replace the body from <image1> with the body "
               "from <image2>, strictly preserving the clothing, body shape and proportions "
               "from <image2>. copy the pose, direction of the eye, head rotation, micro "
               "expressions from <image1>")

INPUTS = [
    ("in_scene",
     'a woman in a blue denim jacket standing on a rainy city street at night, a large neon '
     'shop sign reading "FREE GPU LAB" glowing above the storefront behind her, reflections '
     'on wet pavement, 50mm photo', 1408, 1408),
    ("in_head",
     'studio portrait headshot of a young woman with curly red hair, green eyes and freckles, '
     'neutral expression, plain light gray background, soft studio lighting, sharp focus on '
     'the face, photorealistic', 1024, 1024),
    ("in_person",
     'full body studio reference photo of a young woman with curly red hair, green eyes and '
     'freckles, wearing a blue denim jacket and jeans, standing upright on both feet, facing '
     'the camera, front view, camera at chest height and perfectly level, arms relaxed at the '
     'sides, neutral expression, plain seamless light background, soft even studio lighting, '
     'no props and no cast shadows on the backdrop, the person fills almost the whole height '
     'of the square frame from the top of the head down to the shoes, sharp photographic '
     'detail', 768, 768),
]

T0 = time.time()
TIM = {"run": "bfs-qwen21-t4", "surface": SURFACE, "surface_proof": SURFACE_PROOF,
       "flags": FLAGS, "seed": SEED,
       "bfs_repo": "Alissonerdx/BFS-Best-Face-Swap",
       "prompt_head": HEAD_PROMPT, "prompt_body": BODY_PROMPT,
       "sampler_ladder": SAMPLER_LADDER,
       "rows": [], "downloads": [], "preflight": {}, "eval": {}}


def log(m):
    print(f"[{time.time() - T0:8.1f}s] {m}", flush=True)


def save():
    os.makedirs(OUT, exist_ok=True)
    with open(f"{OUT}/timings_bfs.json", "w") as f:
        json.dump(TIM, f, indent=2)


def sh(cmd, timeout=1800):
    t0 = time.time()
    r = subprocess.run(cmd, shell=True, text=True, timeout=timeout)
    return r.returncode, time.time() - t0


def expected_size(url):
    req = urllib.request.Request(url, method="HEAD")
    with urllib.request.urlopen(req, timeout=60) as r:
        return int(r.headers.get("Content-Length") or 0)


def wget_or_die(url, dest, min_bytes=1e6):
    """Resume-until-complete (v5 kernel lesson: HF egress stalls mid-file)."""
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    want = expected_size(url)
    if os.path.exists(dest) and os.path.getsize(dest) >= min_bytes and (
            not want or os.path.getsize(dest) >= want):
        log(f"cached: {os.path.basename(dest)}")
        return 0.0
    t0 = time.time()
    for attempt in range(1, 9):
        rc = subprocess.run(["wget", "-q", "-c", "--tries=3", "--timeout=120",
                             "--waitretry=10", "-O", dest, url]).returncode
        size = os.path.getsize(dest) if os.path.exists(dest) else 0
        if rc == 0 and size >= min_bytes and (not want or size >= want):
            dt = time.time() - t0
            log(f"download {os.path.basename(dest)} {size/1e9:.2f} GB in {dt:.1f}s "
                f"(attempt {attempt})")
            return dt
        log(f"download attempt {attempt} incomplete rc={rc} "
            f"{size/1e9:.2f}/{want/1e9:.2f} GB — resuming")
        time.sleep(10)
    sys.exit(f"download failed after retries: {url}")


def setup():
    log("=== setup: ComfyUI + nodes + weights (skipped if present) ===")
    if not os.path.isdir(C):
        rc, dt = sh(f"git clone --depth 1 https://github.com/comfyanonymous/ComfyUI {C}")
        log(f"clone ComfyUI rc={rc} {dt:.1f}s")
        rc, dt = sh(f"pip install -q -r {C}/requirements.txt 2>&1 | tail -3", timeout=1200)
        log(f"pip comfy requirements rc={rc} {dt:.1f}s")
    gg = f"{C}/custom_nodes/ComfyUI-GGUF"
    if not os.path.isdir(gg):
        rc, dt = sh(f"git clone --depth 1 https://github.com/leejet/ComfyUI-GGUF {gg}")
        log(f"clone ComfyUI-GGUF rc={rc} {dt:.1f}s")
        rc, dt = sh(f"pip install -q -r {gg}/requirements.txt 2>&1 | tail -3", timeout=1200)
        log(f"pip gguf requirements rc={rc} {dt:.1f}s")
    res = f"{C}/custom_nodes/RES4LYF"
    if not os.path.isdir(res):
        rc, dt = sh(f"git clone --depth 1 https://github.com/ClownsharkBatwing/RES4LYF {res}")
        log(f"clone RES4LYF rc={rc} {dt:.1f}s")
        req = f"{res}/requirements.txt"
        if os.path.exists(req):
            sh(f"pip install -q -r {req} 2>&1 | tail -2", timeout=900)
    dst = f"{C}/custom_nodes/viggle_turbo.py"
    if not os.path.exists(dst):
        rc = subprocess.run(["wget", "-q", "--tries=3", "--timeout=60", "-O", dst,
                             NODES_URL]).returncode
        log(f"viggle_turbo.py rc={rc}")
    mdir = f"{C}/models"
    for url, dest, minb in [
        (TE_URL, f"{mdir}/text_encoders/{TE_NAME}", 9e9),
        (VAE_URL, f"{mdir}/vae/{VAE_NAME}", 6e8),
        (DIT_INT8_URL, f"{mdir}/diffusion_models/{DIT_INT8_NAME}", 7e9),
        (GGUF_URL, f"{mdir}/diffusion_models/{GGUF_NAME}", 4e9),
        (f"{BFS_BASE}/{BFS_HEAD}", f"{mdir}/loras/{BFS_HEAD}", 2.5e8),
        (f"{BFS_BASE}/{BFS_BODY}", f"{mdir}/loras/{BFS_BODY}", 2e8),
        (f"{PRUNA_BASE}/{LORA_PRUNA8}", f"{mdir}/loras/{LORA_PRUNA8}", 3e8),
        (f"{VIGGLE_BASE}/{LORA_VIGGLE_R256}", f"{mdir}/loras/{LORA_VIGGLE_R256}", 1e9),
    ]:
        dt = wget_or_die(url, dest, minb)
        if dt:
            TIM["downloads"].append({"file": os.path.basename(dest), "download_s": round(dt, 1),
                                     "size_gb": round(os.path.getsize(dest) / 1e9, 2)})
        save()
    os.makedirs(f"{mdir}/unet", exist_ok=True)
    if not os.path.exists(f"{mdir}/unet/{GGUF_NAME}"):
        subprocess.run(["cp", f"{mdir}/diffusion_models/{GGUF_NAME}", f"{mdir}/unet/"])
    os.makedirs(f"{mdir}/clip", exist_ok=True)
    if not os.path.exists(f"{mdir}/clip/{TE_NAME}"):
        subprocess.run(["cp", f"{mdir}/text_encoders/{TE_NAME}", f"{mdir}/clip/"])
    log("setup complete")


def http_json(path, payload=None, timeout=60):
    if payload is not None:
        req = urllib.request.Request(BASE + path, data=json.dumps(payload).encode(), method="POST",
                                     headers={"Content-Type": "application/json"})
    else:
        req = urllib.request.Request(BASE + path, method="GET")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def wait_server(proc, timeout=300):
    t0 = time.time()
    while time.time() - t0 < timeout:
        if proc.poll() is not None:
            return False
        try:
            http_json("/system_stats", timeout=5)
            return True
        except Exception:
            time.sleep(3)
    return False


BOOT_N = 0
COMFY_LOG_PATH = None


def boot_server():
    """Boot (or reboot) ComfyUI; returns the process. Reboot frees RAM between blocks.
    Kills any zombie server first — run-1 lesson: a script exit without finally
    left boot-1 alive on 8188, the new server died at bind, and the zombie's
    /object_info answered preflight while render() watched the dead process."""
    global proc, BOOT_N, COMFY_LOG_PATH
    subprocess.run("pkill -f 'main.py --listen 127.0.0.1 --port 8188' || true", shell=True)
    time.sleep(3)
    BOOT_N += 1
    COMFY_LOG_PATH = f"{OUT}/comfyui-b{BOOT_N}.log"
    log(f"booting server (boot {BOOT_N}) with {FLAGS}")
    comfy_log = open(COMFY_LOG_PATH, "w")
    proc = subprocess.Popen([sys.executable, "main.py", "--listen", "127.0.0.1",
                             "--port", str(PORT), *FLAGS],
                            cwd=C, stdout=comfy_log, stderr=subprocess.STDOUT)
    if not wait_server(proc):
        tail = subprocess.run(f"tail -30 {COMFY_LOG_PATH}", shell=True,
                              capture_output=True, text=True).stdout
        log(f"BOOT FAILED:\n{tail}")
        sys.exit(2)
    TIM[f"boot{BOOT_N}_s"] = round(time.time() - T0, 1)
    save()
    atexit.register(_kill_server)
    return proc


def _kill_server():
    p = globals().get("proc")
    if p is not None and p.poll() is None:
        p.terminate()
        try:
            p.wait(10)
        except subprocess.TimeoutExpired:
            p.kill()


def preflight():
    """Self-diagnosing node check (v1 lesson: fail in 5s with the enum list, not
    after a 30-min image). Records every enum the ladders depend on."""
    oi = http_json("/object_info", timeout=120)
    req_nodes = ["UNETLoader", "UnetLoaderGGUF", "CLIPLoader", "VAELoader",
                 "LoraLoaderModelOnly", "TextEncodeQwenImage21", "QwenImage21Cache",
                 "EmptyLatentImage", "KSampler", "VAEDecode", "SaveImage", "LoadImage",
                 "ImageScale", "ViggleTurboLora", "ViggleTurboSigmas"]
    missing = [n for n in req_nodes if n not in oi]
    pf = {"missing_nodes": missing, "n_classes": len(oi)}
    if missing:
        sys.exit(f"PREFLIGHT FAIL — missing {missing}; classes sample: "
                 f"{sorted(oi)[:40]}")
    clipl = oi["CLIPLoader"]["input"]["required"]
    pf["clip_types"] = clipl["type"][0] if "type" in clipl else None
    assert "qwen_image" in pf["clip_types"], f"qwen_image not in CLIPLoader types {pf['clip_types']}"
    samplers = oi["KSampler"]["input"]["required"]["sampler_name"][0]
    pf["sampler_available"] = [s for s in SAMPLER_LADDER if s in samplers]
    assert pf["sampler_available"], f"none of {SAMPLER_LADDER} in KSampler enum"
    te = oi["TextEncodeQwenImage21"]
    pf["te_outputs"] = te.get("output", [])
    pf["te_output_names"] = te.get("output_name", [])
    pf["te_inputs"] = sorted(set(list(te["input"].get("required", {})) +
                                 list(te["input"].get("optional", {}))))
    qc = oi["QwenImage21Cache"]
    qc_in = {**qc["input"].get("required", {}), **qc["input"].get("optional", {})}
    # attempt-1 lesson: device/dtype are REQUIRED in API format — pull defaults
    # from the [type, {default: ...}] config shape ('auto'/'default', the author's
    # own widget values); bare [type, default] shapes also handled.
    pf["cache_inputs"] = {}
    for k, v in qc_in.items():
        if isinstance(v, list) and len(v) > 1 and isinstance(v[1], dict):
            pf["cache_inputs"][k] = v[1].get("default", v[1])
        else:
            pf["cache_inputs"][k] = v
    CACHE_DEFAULTS.clear()
    CACHE_DEFAULTS.update({k: v for k, v in pf["cache_inputs"].items()
                           if k != "model" and not isinstance(v, (list, dict))})
    ims = oi["ImageScale"]["input"]
    pf["imagescale_inputs"] = sorted(set(list(ims.get("required", {})) +
                                         list(ims.get("optional", {}))))
    TIM["preflight"] = pf
    save()
    log(f"preflight OK: sampler={pf['sampler_available'][0]} "
        f"te_outputs={pf['te_outputs']} te_inputs={pf['te_inputs']}")
    return pf


# --- graph builders -----------------------------------------------------------

def turbo_t2i(prompt, w, h, prefix):
    """viggle r256 6-step turbo (proven v4-v6): for consent-free input generation."""
    return {
        "1": {"class_type": "UnetLoaderGGUF", "inputs": {"unet_name": GGUF_NAME}},
        "2": {"class_type": "CLIPLoader", "inputs": {"clip_name": TE_NAME, "type": "qwen_image"}},
        "3": {"class_type": "VAELoader", "inputs": {"vae_name": VAE_NAME}},
        "4": {"class_type": "CLIPTextEncode", "inputs": {"clip": ["2", 0], "text": prompt}},
        "5": {"class_type": "ViggleTurboLora", "inputs": {"model": ["1", 0],
                                                          "lora_name": LORA_VIGGLE_R256,
                                                          "strength": 1.0}},
        "6": {"class_type": "EmptySD3LatentImage", "inputs": {"width": w, "height": h,
                                                              "batch_size": 1}},
        "7": {"class_type": "RandomNoise", "inputs": {"noise_seed": SEED}},
        "8": {"class_type": "KSamplerSelect", "inputs": {"sampler_name": "euler"}},
        "9": {"class_type": "ViggleTurboSigmas", "inputs": {"latent": ["6", 0],
                                                            "nodes": SIGMAS_6}},
        "10": {"class_type": "BasicGuider", "inputs": {"model": ["5", 0], "conditioning": ["4", 0]}},
        "11": {"class_type": "SamplerCustomAdvanced",
               "inputs": {"noise": ["7", 0], "guider": ["10", 0], "sampler": ["8", 0],
                          "sigmas": ["9", 0], "latent_image": ["6", 0]}},
        "12": {"class_type": "VAEDecode", "inputs": {"samples": ["11", 0], "vae": ["3", 0]}},
        "13": {"class_type": "SaveImage", "inputs": {"images": ["12", 0],
                                                     "filename_prefix": prefix}},
    }


LORA_MAP = {"pruna8": LORA_PRUNA8, "bfs_head": BFS_HEAD, "bfs_body": BFS_BODY}
CACHE_DEFAULTS = {}  # filled from /object_info in preflight
LATENT_OUT_IDX = 2  # corrected in preflight from te_output_names


def bfs_swap(scene_file, head_file, latent_wh, scene_size, ref_size, prefix, sampler,
             loras=(("stock:pruna8", 1.0), ("stock:bfs_head", 1.0)), dit="int8",
             use_cache=True, latent_from_te=False, prompt=HEAD_PROMPT, te_resolution=0,
             warm_crop=False):
    """BFS two-image swap, mirroring the official workflow:
    DiT -> LoraLoaderModelOnly(Pruna8) -> LoraLoaderModelOnly(BFS) -> QwenImage21Cache
    -> KSampler(deis_2m, 8 steps, cfg 1.0) <- TextEncodeQwenImage21(clip, vae, images).
    refs pre-scaled (lanczos): scene to scene_size, head/ref to ref_size; TE
    resolution 0 = refs at own size (the template's own combination). LoRA spec
    keys 'stock:<name>' use the stock merge (author-faithful); 'hook:<name>'
    load through the viggle runtime-hook node (exact update on quantized weights)."""
    g = {}
    if dit == "int8":
        g["1"] = {"class_type": "UNETLoader",
                  "inputs": {"unet_name": DIT_INT8_NAME, "weight_dtype": "default"}}
    else:
        g["1"] = {"class_type": "UnetLoaderGGUF", "inputs": {"unet_name": GGUF_NAME}}
    g["2"] = {"class_type": "CLIPLoader", "inputs": {"clip_name": TE_NAME, "type": "qwen_image"}}
    g["3"] = {"class_type": "VAELoader", "inputs": {"vae_name": VAE_NAME}}
    g["10"] = {"class_type": "LoadImage", "inputs": {"image": scene_file}}
    g["11"] = {"class_type": "LoadImage", "inputs": {"image": head_file}}
    g["12"] = {"class_type": "ImageScale",
               "inputs": {"upscale_method": "lanczos", "width": scene_size,
                          "height": scene_size,
                          "crop": "center" if warm_crop else "disabled",
                          "image": ["10", 0]}}
    g["13"] = {"class_type": "ImageScale",
               "inputs": {"upscale_method": "lanczos", "width": ref_size,
                          "height": ref_size, "crop": "disabled", "image": ["11", 0]}}
    model_src = "1"
    n = 20
    for name, strength in loras:
        key = name.split(":", 1)[1]
        lora = LORA_MAP[key]
        if name.startswith("hook:"):
            g[str(n)] = {"class_type": "ViggleTurboLora",
                         "inputs": {"model": [model_src, 0], "lora_name": lora,
                                    "strength": strength}}
        else:
            g[str(n)] = {"class_type": "LoraLoaderModelOnly",
                         "inputs": {"model": [model_src, 0], "lora_name": lora,
                                    "strength_model": strength}}
        model_src = str(n)
        n += 1
    if use_cache:
        g[str(n)] = {"class_type": "QwenImage21Cache",
                     "inputs": {"model": [model_src, 0], **CACHE_DEFAULTS}}
        model_src = str(n)
        n += 1
    g["30"] = {"class_type": "TextEncodeQwenImage21",
               "inputs": {"clip": ["2", 0], "vae": ["3", 0], "prompt": prompt,
                          "negative_prompt": "", "resolution": te_resolution,
                          "images": {"image_1": ["12", 0], "image_2": ["13", 0]}}}
    if latent_from_te:
        latent_src = ["30", LATENT_OUT_IDX]
    else:
        g["31"] = {"class_type": "EmptyLatentImage",
                   "inputs": {"width": latent_wh, "height": latent_wh, "batch_size": 1}}
        latent_src = ["31", 0]
    g["32"] = {"class_type": "KSampler",
               "inputs": {"model": [model_src, 0], "positive": ["30", 0],
                          "negative": ["30", 1], "latent_image": latent_src,
                          "seed": SEED, "steps": 8, "cfg": 1.0,
                          "sampler_name": sampler, "scheduler": "simple", "denoise": 1.0}}
    g["33"] = {"class_type": "VAEDecode", "inputs": {"samples": ["32", 0], "vae": ["3", 0]}}
    g["34"] = {"class_type": "SaveImage", "inputs": {"images": ["33", 0],
                                                     "filename_prefix": prefix}}
    return g


# --- submit + render ----------------------------------------------------------

_seen_graph_hashes = set()


def submit(graph):
    """POST /prompt with ladders; returns (prompt_id, None) or (None, error_str).
    Autogrow images API format = FLAT dotted keys ('images.image_1') — the
    server's _resolve_dynamic_paths pops those keys and nests them itself.
    Attempt-2 lesson: a nested dict {'images': {...}} validates AND executes
    silently with zero images bound (all swap rows became pure t2i), so flat
    goes first and the nested form is only a fallback."""
    for fmt, mutate in (
        ("flat", lambda gg: _flatten_autogrow(gg)),
        ("nested", lambda gg: gg),
    ):
        gg = json.loads(json.dumps(mutate(graph)))
        try:
            r = http_json("/prompt", {"prompt": gg, "client_id": "w40bfs"}, timeout=120)
            return r["prompt_id"], None
        except urllib.error.HTTPError as e:
            body = e.read().decode(errors="replace")
            log(f"submit rejected ({fmt}): {body[:300]}")
            if fmt == "flat" and "image" in body:
                continue
            return None, body[:800]
        except Exception as e:
            return None, f"{type(e).__name__}: {e}"
    return None, "submit exhausted"


def _flatten_autogrow(graph):
    for node in graph.values():
        imgs = node.get("inputs", {}).get("images")
        if isinstance(imgs, dict):
            for k, v in imgs.items():
                node["inputs"][f"images.{k}"] = v
            del node["inputs"]["images"]
    return graph


def comfy_vram():
    try:
        st = http_json("/system_stats", timeout=10)
        dev = st.get("devices", [{}])[0]
        return {"vram_free_gb": round(dev.get("vram_free", 0) / 1e9, 2),
                "vram_total_gb": round(dev.get("vram_total", 0) / 1e9, 2)}
    except Exception:
        return {}


def ram_gb():
    try:
        with open("/proc/meminfo") as f:
            info = {l.split(":")[0]: int(l.split()[1]) for l in f if ":" in l}
        return round((info["MemTotal"] - info["MemAvailable"]) / 1e6, 2)
    except Exception:
        return None


def render(name, graph, comfy_log_path, poll_s=1800, meta=None):
    """Run one graph to completion; download PNGs; record wall/stats."""
    h = hashlib.md5(json.dumps(graph, sort_keys=True).encode()).hexdigest()
    assert h not in _seen_graph_hashes, f"graph for {name} duplicates an earlier row (cache-hit risk)"
    _seen_graph_hashes.add(h)
    rec = {"key": name, "graph_md5": h, "meta": meta or {},
           "ram_used_gb": ram_gb(), **comfy_vram()}
    t0 = time.time()
    pid, err = submit(graph)
    if pid is None:
        rec.update({"ok": False, "wall_s": round(time.time() - t0, 1), "note": f"submit: {err}"})
        TIM["rows"].append(rec)
        save()
        return rec
    ok, imgs, note = False, [], ""
    while time.time() - t0 < poll_s:
        time.sleep(3)
        if proc.poll() is not None:
            note = "server process died"
            break
        try:
            hist = http_json(f"/history/{pid}", timeout=15)
        except Exception:
            continue
        if pid not in hist:
            continue
        entry = hist[pid]
        status = entry.get("status", {})
        imgs = [im["filename"] for o in entry.get("outputs", {}).values()
                for im in o.get("images", [])]
        if status.get("status_str") == "error":
            msgs = json.dumps(status.get("messages", []))
            note = f"comfy error: {msgs[:400]}"
            break
        if imgs:
            ok, note = True, "ok"
            break
    rec.update({"ok": ok, "wall_s": round(time.time() - t0, 1), "note": note, "files": imgs})
    log(f"{name}: ok={ok} {rec['wall_s']}s ({note[:120]})")
    if ok:
        saved = []
        for fn in imgs:
            data = urllib.request.urlopen(
                f"{BASE}/view?filename={urlquote(fn)}&subfolder=&type=output",
                timeout=120).read()
            dest = f"{OUT}/{fn}"
            with open(dest, "wb") as f:
                f.write(data)
            saved.append(fn)
        rec["saved"] = saved
        rec.update(post_render_stats(comfy_log_path))
        rec["ram_used_gb_after"] = ram_gb()
        rec.update(comfy_vram())
    TIM["rows"].append(rec)
    save()
    return rec


def post_render_stats(comfy_log_path):
    rec = {}
    try:
        logtxt = open(comfy_log_path).read()
        it_lines = re.findall(r"(\d+)/(\d+) \[[0-9:]+<[0-9:]+, +([0-9.]+)s/it", logtxt)
        rec["s_per_step"] = it_lines[-1][2] if it_lines else None
        ex = re.findall(r"Prompt executed in ([0-9:.]+)", logtxt)
        rec["executed_s"] = ex[-1] if ex else None
    except Exception:
        pass
    return rec


def swap_inputs_to_input_dir(rec, name):
    """Copy a generated input PNG from ComfyUI/output to ComfyUI/input for LoadImage."""
    fn = rec["files"][0]
    src = f"{C}/output/{fn}"
    dst = f"{C}/input/{name}.png"
    subprocess.run(["cp", src, dst], check=True)
    return f"{name}.png"


# --- quality eval -------------------------------------------------------------

def ssim_gray(a_path, b_path, bottom_frac=None, size=256):
    """Coarse block-SSIM on grayscale; lower = more drift. bottom_frac crops to
    the lower part of the frame (below the head) before resize."""
    from PIL import Image
    import numpy as np
    def prep(p):
        im = Image.open(p).convert("L")
        w, h = im.size
        if bottom_frac:
            im = im.crop((0, int(h * (1 - bottom_frac)), w, h))
        return np.asarray(im.resize((size, size), Image.LANCZOS), dtype=np.float64) / 255.0
    a, b = prep(a_path), prep(b_path)
    C1, C2, win = (0.01) ** 2, (0.03) ** 2, 8
    m = size // win
    ba, bb = a.reshape(m, win, m, win), b.reshape(m, win, m, win)
    a, b = ba.mean(axis=(1, 3)), bb.mean(axis=(1, 3))
    va, vb = ba.var(axis=(1, 3)), bb.var(axis=(1, 3))
    cov = (ba * bb).mean(axis=(1, 3)) - a * b
    s = ((2 * a * b + C1) * (2 * cov + C2)) / ((a * a + b * b + C1) * (va + vb + C2))
    return round(float(s.mean()), 4)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def face_model():
    """Best-effort ArcFace via insightface (CPU). Returns embed fn or None."""
    try:
        from PIL import Image
        import numpy as np
        from insightface.app import FaceAnalysis
        app = FaceAnalysis(name="buffalo_l", providers=["CPUExecutionProvider"])
        app.prepare(ctx_id=-1, det_size=(640, 640))

        def embed(path):
            img = np.asarray(Image.open(path).convert("RGB"))[:, :, ::-1]
            faces = app.get(img)
            if not faces:
                return None
            f = max(faces, key=lambda x: (x.bbox[2] - x.bbox[0]) * (x.bbox[3] - x.bbox[1]))
            return f.normed_embedding
        return embed
    except Exception as e:
        log(f"insightface unavailable: {type(e).__name__}: {e}")
        return None


def evaluate():
    """Identity sims (if ArcFace available) + background SSIM per swap output."""
    ev = TIM.setdefault("eval", {})
    from PIL import Image  # noqa
    scene_png = next((f"{OUT}/{r['files'][0]}" for r in TIM["rows"]
                      if r.get("ok") and r["files"] and r["key"] == "gen_in_scene"), None)
    head_png = next((f"{OUT}/{r['files'][0]}" for r in TIM["rows"]
                     if r.get("ok") and r["files"] and r["key"] == "gen_in_head"), None)
    if scene_png and head_png:
        for r in TIM["rows"]:
            if not (r.get("ok") and r.get("files")):
                continue
            out = f"{OUT}/{r['files'][0]}"
            if r["key"] == "gen_in_scene":
                continue
            ev.setdefault("bg_ssim", {})[r["key"]] = {
                "full": ssim_gray(out, scene_png),
                "bottom45": ssim_gray(out, scene_png, bottom_frac=0.45),
            }
        ev["canary_note"] = ("FREE GPU LAB neon legibility eyeballed from committed PNGs; "
                             "see README. SSIM here is quantitative background drift only.")
        embed = None
        try:
            r = subprocess.run(["pip", "install", "-q", "insightface", "onnxruntime"],
                               capture_output=True, text=True, timeout=420)
            log(f"pip insightface rc={r.returncode}")
            embed = face_model()
        except Exception as e:
            log(f"insightface install failed: {e}")
        ev["arcface"] = {"available": embed is not None}
        if embed:
            import numpy as np
            e_scene, e_head = embed(scene_png), embed(head_png)
            sims = {}
            for r in TIM["rows"]:
                if not (r.get("ok") and r.get("files")) or r["key"] == "gen_in_scene":
                    continue
                e = embed(f"{OUT}/{r['files'][0]}")
                if e is None or e_scene is None or e_head is None:
                    sims[r["key"]] = {"face_detected": e is not None}
                    continue
                sims[r["key"]] = {
                    "sim_vs_refhead": round(float(np.dot(e, e_head)), 4),
                    "sim_vs_sceneperson": round(float(np.dot(e, e_scene)), 4),
                }
            ev["arcface"]["rows"] = sims
            ev["arcface"]["note"] = ("sim_vs_refhead should rise on BFS rows (identity "
                                     "transferred) and stay low on the anchor; "
                                     "sim_vs_sceneperson the reverse. 1.0 = identical.")
    for r in TIM["rows"]:
        if r.get("files"):
            r["sha256"] = {fn: sha256(f"{OUT}/{fn}") for fn in r["files"]}
    save()


# --- main ---------------------------------------------------------------------

def main():
    global LATENT_OUT_IDX
    os.makedirs(OUT, exist_ok=True)
    setup()
    boot_server()
    pf = preflight()
    if "latent" in pf["te_output_names"]:
        LATENT_OUT_IDX = pf["te_output_names"].index("latent")
    sampler = pf["sampler_available"][0]
    log(f"sampler for all rows: {sampler}")

    # -- consent-free inputs via the proven turbo pipeline (seed 42);
    # attempt-3 rerun reuses the input PNGs already in ComfyUI/input when present
    input_files = {}
    for key, prompt, w, h in INPUTS:
        if os.path.exists(f"{C}/input/{key}.png"):
            input_files[key] = f"{key}.png"
            log(f"input cached: {key}.png")
            continue
        rec = render(f"gen_{key}", turbo_t2i(prompt, w, h, f"bfsin_{key}"), COMFY_LOG_PATH)
        if rec["ok"]:
            input_files[key] = swap_inputs_to_input_dir(rec, key)
        else:
            sys.exit(f"input generation failed for {key}: {rec['note']}")

    # -- int8 block (official recipe)
    render("R1_head_official_1408_cold",
           bfs_swap(input_files["in_scene"], input_files["in_head"], 1408, 768, 512,
                    "bfsR1_head1408", sampler),
           COMFY_LOG_PATH, poll_s=2400,
           meta={"dit": "int8", "loader": "stock_merge", "loras": [LORA_PRUNA8, BFS_HEAD],
                 "latent": 1408, "refs": [768, 512], "ref_note": "T4 adaptation: refs pre-scaled down (docstring)"})
    if proc.poll() is None:
        render("R2_head_official_1408_warm",
               bfs_swap(input_files["in_scene"], input_files["in_head"], 1408, 768, 512,
                        "bfsR2_head1408b", sampler, warm_crop=True),
               COMFY_LOG_PATH, poll_s=2400,
               meta={"dit": "int8", "loader": "stock_merge", "loras": [LORA_PRUNA8, BFS_HEAD],
                     "latent": 1408, "refs": [768, 512], "warm": True,
                     "warm_trick": ("scene ImageScale crop disabled->center: same pixels, "
                                    "different node hash, forces upstream re-execution "
                                    "(attempt-2 lesson: prefix-only change still hit the "
                                    "per-node execution cache)")})
    if proc.poll() is None:
        render("R3_head_official_1024",
               bfs_swap(input_files["in_scene"], input_files["in_head"], 1024, 768, 512,
                        "bfsR3_head1024", sampler),
               COMFY_LOG_PATH,
               meta={"dit": "int8", "loader": "stock_merge", "loras": [LORA_PRUNA8, BFS_HEAD],
                     "latent": 1024, "refs": [768, 512]})
    if proc.poll() is None:
        render("R4_anchor_nobfs_1024",
               bfs_swap(input_files["in_scene"], input_files["in_head"], 1024, 768, 512,
                        "bfsR4_anchor1024", sampler,
                        loras=(("stock:pruna8", 1.0),)),
               COMFY_LOG_PATH,
               meta={"dit": "int8", "loader": "stock_merge", "loras": [LORA_PRUNA8],
                     "latent": 1024, "refs": [768, 512], "note": "no-BFS anchor"})
    if proc.poll() is None:
        render("R7_body_swap_1408",
               bfs_swap(input_files["in_scene"], input_files["in_person"], 1408, 768, 768,
                        "bfsR7_body1408", sampler,
                        loras=(("stock:pruna8", 1.0), ("stock:bfs_body", 1.0)),
                        latent_from_te=True, prompt=BODY_PROMPT),
               COMFY_LOG_PATH, poll_s=2400,
               meta={"dit": "int8", "loader": "stock_merge",
                     "loras": [LORA_PRUNA8, BFS_BODY], "latent": "te_latent(scene-sized)",
                     "refs": [768, 768], "prompt": "body_swap"})

    # -- restart (RAM), GGUF block
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(10)
        except subprocess.TimeoutExpired:
            proc.kill()
        boot_server()
        pf2 = preflight()
        if "latent" in pf2["te_output_names"]:
            LATENT_OUT_IDX = pf2["te_output_names"].index("latent")
        sampler = pf2["sampler_available"][0]
        render("R5_head_gguf_hook_1024",
               bfs_swap(input_files["in_scene"], input_files["in_head"], 1024, 768, 512,
                        "bfsR5_ggufhook", sampler, dit="gguf", use_cache=False,
                        loras=(("hook:pruna8", 1.0), ("hook:bfs_head", 1.0))),
               COMFY_LOG_PATH,
               meta={"dit": "gguf", "loader": "viggle_hook",
                     "loras": [LORA_PRUNA8, BFS_HEAD], "latent": 1024, "refs": [768, 512],
                     "note": "cache node dropped on GGUF path"})
        if proc.poll() is None:
            render("R6_head_gguf_merge_1024",
                   bfs_swap(input_files["in_scene"], input_files["in_head"], 1024, 768, 512,
                            "bfsR6_ggufmerge", sampler, dit="gguf", use_cache=False,
                            loras=(("stock:pruna8", 1.0), ("stock:bfs_head", 1.0))),
                   COMFY_LOG_PATH,
                   meta={"dit": "gguf", "loader": "stock_merge",
                         "loras": [LORA_PRUNA8, BFS_HEAD], "latent": 1024,
                         "refs": [768, 512]})

    evaluate()
    TIM["total_s"] = round(time.time() - T0, 1)
    TIM["success"] = any(r["ok"] for r in TIM["rows"] if r["key"].startswith(("R1", "R2", "R3", "R5", "R6")))
    save()
    subprocess.run(f"tar czf {OUT}.tar.gz -C {os.path.dirname(OUT)} {os.path.basename(OUT)}",
                   shell=True)
    log(f"=== DONE success={TIM['success']} total={TIM['total_s']}s ===")
    print("=== TIMINGS_BFS_JSON ===", flush=True)
    print(json.dumps(TIM, indent=2), flush=True)
    sys.exit(0 if TIM["success"] else 1)


if __name__ == "__main__":
    main()
